version: '3.5'

services:
  front-nginx:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    links:
      - back-nodejs
    depends_on:
      - back-nodejs

  back-nodejs:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
